embention/RTD#89 Changes to RTD_Core templates.
embention/RTD_core pull request #12
Opened 2023-04-17 10:02 UTC by arc26

# References
https://github.com/embention/RTD/issues/89

# Changelog

>* Added: `custom.js` - Fix for Mirage bug
>* Changed:  `layout.html` - Changed the JavaScript references

# Description
This pull request must be reviewed with the following pull request https://github.com/embention/RTD/pull/145

Added the new script that fixes the errors that were happening in mobile devices. Changed the base template for html files in order to include this script. In order to test this, generate a manual and check if the changes have been applied properly.

2023-04-17 10:19 UTC, das2 submitted a review, later dismissed
- [x] Si el archivo `sphinx_press_custom/sphinx_press_theme/_static/custom.js` sustituye al archivo 'sphinx_press_custom/sphinx_press_theme/_static/theme.js', el segundo debería ser eliminado del repositorio y no se observa dicho cambio en el pull request.
- [x] `sphinx_press_custom/sphinx_press_theme/static/custom.js` se ve que la carpeta `static` no tiene un underscore, es decir `_static`, probablemente sea correcto, pero comprobar que lo sea.

2023-04-17 10:53 UTC, arc26 commented
@das2 
Cambios aplicados en https://github.com/embention/RTD_core/pull/12/commits/0732e4a9ee31071029f3320f9814a99f69634e37

2023-04-17 11:54 UTC, jrc4 approved these changes
Parece correcto

2023-04-17 12:20 UTC, jrc4 requested changes
- [ ] Tras el último análisis en RTD#145 https://github.com/embention/RTD/pull/145#pullrequestreview-1387894703 se detecta que se deben tener en cuenta los archivos minificados para las rutas del servidor. Comprobar que no existen conflictos con los archivos que se extraen del RTD_Core y las rutas que deben ser utilizadas en el RTD_Server_Flask

2023-04-17 12:35 UTC, arc26 commented
> * [ ]  Tras el último análisis en RTD#145 [Feature/89 rtd responsive design errors RTD#145 (review)](https://github.com/embention/RTD/pull/145#pullrequestreview-1387894703) se detecta que se deben tener en cuenta los archivos minificados para las rutas del servidor. Comprobar que no existen conflictos con los archivos que se extraen del RTD_Core y las rutas que deben ser utilizadas en el RTD_Server_Flask

Se procede a minificar los archivos afectados en esta pull request para que a la hora del despliegue no sea necesario minificar cada archivo individualmente.

2023-04-17 12:43 UTC, jrc4 approved these changes, later dismissed

2023-04-17 13:53 UTC, arc26 commented
Se añade el commit https://github.com/embention/RTD_core/pull/12/commits/3fc11b1b42535780e639417e5e99b5ea04612c2b para implementar el archivo minificado que funciona.

2023-04-17 15:20 UTC, jrc4 approved these changes, later dismissed
Parece correcto

2023-04-19 08:20 UTC, jrc4 approved these changes
Parece Correcto

2023-04-19 11:15 UTC, merged