embention/IT#1308 Indented text is not displayed with gray color
embention/RTD_core pull request #19
Opened 2023-10-23 10:44 UTC by ace38

# References

https://github.com/embention/Tools/issues/1308

# Changelog

- Changed: custom.css and custom_style.css have been changed to display indented text as black

2023-10-25 13:14 UTC, jrc4 requested changes
- [ ] Se está modificando la forma en que se muestran los BlockQuotes que sirven para añadir citas al texto. Se debería comprobar que no existe ninguna otra forma de añadir sangrado a los documentos antes de cambiar este comportamiento base del estilo de RTD.
  - [ ] En caso de que se quiera eliminar el estilo de los BlockQuotes puede que baste con borrar la entrada CSS por completo en lugar de modificar su aspecto
- [ ] Realizar comprobaciones para ver como se comporta el documento cuando se le añaden varias tabulaciones a una línea de texto. Esto es importante porque puede que al anidar varios BlockQuotes el comportamiento sea diferente.

2023-10-25 13:14 UTC, jrc4 commented on _static/custom_style.css
> +}
```suggestion
}

```

2023-10-27 09:37 UTC, ace38 commented
> * [x]  Se está modificando la forma en que se muestran los BlockQuotes que sirven para añadir citas al texto. Se debería comprobar que no existe ninguna otra forma de añadir sangrado a los documentos antes de cambiar este comportamiento base del estilo de RTD.

Desde Scripts nos hemos roto los cuernos varias veces para tabular sin que salga en gris y no hubo manera.

>   * [x]  En caso de que se quiera eliminar el estilo de los BlockQuotes puede que baste con borrar la entrada CSS por completo en lugar de modificar su aspecto

He borrado por completo los BlockQuotes

> * [x]  Realizar comprobaciones para ver como se comporta el documento cuando se le añaden varias tabulaciones a una línea de texto. Esto es importante porque puede que al anidar varios BlockQuotes el comportamiento sea diferente.

Tras borrar los blockquotes, he comprobado que se puede tabular varios niveles sin problema. No afecta a las sublistas.

2023-11-02 12:51 UTC, jrc4 requested changes
Eliminar los estilos de los `blockquote` hace que el archivo se vea como se quiere pero siguen existiendo etiquetas `blockquote` en el código HTML cuando se añaden tabulaciones.
Esto podría causar problemas de formateo, con imágenes inline por ejemplo.
Se debería al menos plantear si es posible evitar que el compilador de Sphinx/LaTeX añada etiquetas `blockquote` cuando se añaden tabulaciones.
Alternativamente se podrían usar otros símbolos para las `blockquotes` y así no perderíamos la funcionalidad de añadir quotes a los textos.

2023-11-02 14:42 UTC, das2 commented
Respecto el comentario de @jrc4 https://github.com/embention/RTD_core/pull/19#pullrequestreview-1710163232 y en general el pull:

Hay que tener en cuenta que si, esta issue es para cambiar los estilos, pero si el problema en realidad proviene de un mal uso de los formatos disponibles con RST, ajustar los estilos en lugar de aprender los formatos puede ser contraproducente y casusar "deuda técnica" si a futuro se decide cambiar de tema.

En resumen, se deberían dar indicaciones de que los editores de RST no empleen tabulaciones cuando no tocan, y yo seguiría las opciones de formato disponibles con el [tema de RTD "básico"](https://sphinx-rtd-theme.readthedocs.io/en/stable/).

Señalizando que soy consciente de que cuando se implementó el tema de estilos actual yo ya advertí de malos estilos respecto a formatos respecto al [tema de RTD "básico"](https://sphinx-rtd-theme.readthedocs.io/en/stable/), por  lo que quizás lo que estáis indicando va en linea con esto último y el desarrollo que llevéis sea el correcto.

Básicamente comento todo esto para que seáis conscientes de la problemática de editar estilos de tema y/o formar en el uso de RST.

2023-11-03 10:36 UTC, ace38 commented
> Respecto el comentario de @jrc4 [#19 (review)](https://github.com/embention/RTD_core/pull/19#pullrequestreview-1710163232) y en general el pull:
> 
> Hay que tener en cuenta que si, esta issue es para cambiar los estilos, pero si el problema en realidad proviene de un mal uso de los formatos disponibles con RST, ajustar los estilos en lugar de aprender los formatos puede ser contraproducente y casusar "deuda técnica" si a futuro se decide cambiar de tema.
> 
> En resumen, se deberían dar indicaciones de que los editores de RST no empleen tabulaciones cuando no tocan, y yo seguiría las opciones de formato disponibles con el [tema de RTD "básico"](https://sphinx-rtd-theme.readthedocs.io/en/stable/).
> 
> Señalizando que soy consciente de que cuando se implementó el tema de estilos actual yo ya advertí de malos estilos respecto a formatos respecto al [tema de RTD "básico"](https://sphinx-rtd-theme.readthedocs.io/en/stable/), por lo que quizás lo que estáis indicando va en linea con esto último y el desarrollo que llevéis sea el correcto.
> 
> Básicamente comento todo esto para que seáis conscientes de la problemática de editar estilos de tema y/o formar en el uso de RST.

Entonces el problema no viene causado por un fallo de la herramienta, sino por un mal uso de la misma. Desde este enfoque, la solución consiste en modificar el procedimiento de edición de manuales P.186 para que los editores sepan que tabular sirve para redactar citas.

2023-11-03 10:36 UTC, closed without merging